#set ft=ansible
---
- name: get the default ip of localhost
  hosts: localhost
  tasks:
    - debug:
        var: ansible_default_ipv4.address

- name: Test access to bastion by setting motd
  tags:
    - checkpoint0
  hosts:
    - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_bastion') | replace('-', '_') }}"
  remote_user: cloud-user
  become: true
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
  tasks:
    - name: bastion ansible_host
      debug:
        var: ansible_host
    - name: bastion ip
      debug:
        var: ansible_default_ipv4.address
    - copy:
        content: "Welcome to Bastion. We hope you enjoy your stay.\n"
        dest: /etc/motd
      register: motd_changed
      until: motd_changed | success
      retries: 3
      delay: 25
    - debug:
        var: ansible_host

- name: checkpoint-freeze
  include: '{{ ANSIBLE_REPO_PATH }}/cloud_providers/{{ cloud_provider }}/checkpoint-freeze.yml checkpoint_id=checkpoint1 tags=checkpoint0 milestone'

