# vim: set ft=ansible:
---
######################## Install Basic Packages
- name: Install Basic Packages
  include: ./packages.yml
  tags:
    - install_basic_packages


- name: clean repositories
  shell: "yum clean all"
  when: clear_yum_cache

######################### Run a complete yum update
- name: Update all packages
  yum:
    name: '*'
    state: latest
  when: update_packages
