- name: Step 002 Post Infrastructure
  hosts: localhost
  connection: local
  become: false
  tags:
    - step002
    - post_infrastructure
- name: Set passwords on bastion and osp nodes
  hosts: "{{ ('tag_Project_' ~ env_type ~ '_' ~ guid) | replace('-', '_') }}"
  become: true
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/ssh_vars.yml"
  tasks:
    - name: register hashed password
      command: openssl passwd {{ default_password }}
      register: hashed_pw
    - name: set passwords
      command: sudo usermod -p {{ hashed_pw.stdout }} root
    - shell: "ip addr show eth1 | gawk 'match($0, /link\\/ether/) {print $2}'"
      register: cntrlr_eth1_mac_output
- name: Enable dhcp for eth1 on compute node
  hosts: "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_controller') | replace('-', '_') }}"
  become: true
  vars:
    - controller_eth1_hwaddr: "{{ cntrlr_eth1_mac_output.stdout }}"
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/ssh_vars.yml"
  tasks:
    - debug:
        var: controller_eth1_hwaddr
    - template:
        src: "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/files/ifcfg-eth1"
        dest: "/etc/sysconfig/network-scripts/ifcfg-eth1"
    - template:
        src: "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/files/ifcfg-br-ex"
        dest: "/etc/sysconfig/network-scripts/ifcfg-br-ex"
    - lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0
        line: 'IPV6INIT=NO'
