# vim: set ft=ansible:
---
- name: Add opentlc-mgr
  shell: "useradd opentlc-mgr"
  ignore_errors: true
- shell: "rm -rf /opt/ansible_agnostic_deployer"
- name: Get updated files from git repository github.com/sborenst/ansible_agnostic_deployer
  git: repo=https://{{ githubuser }}:{{ githubpassword }}@github.com/sborenst/ansible_agnostic_deployer.git dest=/opt/ansible_agnostic_deployer/ force=yes
  ignore_errors: true

- shell: "rm -rf /opt/OPEN_Admin"
- name: Get updated files from git repository github.com/redhat-gpe/OPEN_Admin.git
  git: repo=https://{{ githubuser }}:{{ githubpassword }}@github.com/redhat-gpe/OPEN_Admin.git dest=/opt/OPEN_Admin/ force=yes
  ignore_errors: true

- file: "path=/opt/OPEN_Admin/ state=directory owner=opentlc-mgr recurse=yes group=opentlc-mgr  mode=0770"
- file: "path=/opt/ansible_agnostic_deployer/ state=directory owner=opentlc-mgr recurse=yes group=opentlc-mgr  mode=0770"
- shell: "cp -rf /root/.kube /home/opentlc-mgr/"
  ignore_errors: true
- shell: "chown -R opentlc-mgr.opentlc-mgr /home/opentlc-mgr/.kube"
  ignore_errors: true
- shell: |
      mkdir /home/opentlc-mgr/bin;
      ln -s /opt/OPEN_Admin/OPENTLC-OCP3/provision-ose-projects.sh /home/opentlc-mgr/bin/provision-accounts.sh
      ln -s /opt/OPEN_Admin/OPENTLC-OCP3/provision-ose-projects.sh /home/opentlc-mgr/bin/provision-ose-projects.sh
      mkdir /home/opentlc-mgr/.ssh
      echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4OojwKH74UWVOY92y87Tb/b56CMJoWbz2gyEYsr3geOc2z/n1pXMwPfiC2KT7rALZFHofc+x6vfUi6px5uTm06jXa78S7UB3MX56U3RUd8XF3svkpDzql1gLRbPIgL1h0C7sWHfr0K2LG479i0nPt/X+tjfsAmT3nWj5PVMqSLFfKrOs6B7dzsqAcQPInYIM+Pqm/pXk+Tjc7cfExur2oMdzx1DnF9mJaj1XTnMsR81h5ciR2ogXUuns0r6+HmsHzdr1I1sDUtd/sEVu3STXUPR8oDbXBsb41O5ek6E9iacBJ327G3/1SWwuLoJsjZM0ize+iq3HpT1NqtOW6YBLR opentlc-mgr@inf00-mwl.opentlc.com' >> /home/opentlc-mgr/.ssh/authorized_keys
      chown -R opentlc-mgr.opentlc-mgr /home/opentlc-mgr/.ssh
      chmod 400 /home/opentlc-mgr/.ssh/authorized_keys
      chmod 700 /home/opentlc-mgr/.ssh
  ignore_errors: true
