---
- name: Step 001 Deploy Infrastructure
  hosts: 
    - localhost
    - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_bastion') | replace('-', '_') }}"
  connection: local
  gather_facts: false
  become: false
  vars:
    - cloud_template: "{{ lookup( 'file', '{{ ANSIBLE_REPO_PATH }}/workdir/{{cloud_provider}}_cloud_template.{{ env_type }}.{{ guid }}.template') | from_yaml }}"
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
  tags:
    - step001
    - create_ssh_config
  tasks:
    - name: resolve jmespath dependency
      yum:
        name: python2-jmespath
        state: present
    - name: add bastion host
      add_host:
        name: "{{ ravello_groups | json_query('_meta.hostvars.\"bastion-REPL.rhpds.opentlc.com\".externalFqdn') }}"
        groups: 
        - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_bastion') | replace('-', '_') }}"
        - "{{ ('tag_Project_' ~ env_type ~ '_' ~ guid) | replace('-', '_') }}"
    - name: add remaining hosts
      add_host:
        name: "{{ item['hostnames'].0 }}"
        groups:
          - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_' ~ item.tag ) | replace('-', '_') }}"
          - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_' ~ item.name ) | replace(' ', '_') | replace('-', '_') }}"
          - "{{ ('tag_Project_' ~ env_type ~ '_' ~ guid) | replace('-', '_') }}"
      with_items: "{{ cloud_template['vms'] }}"
      when: item.tag != 'bastion'

    - debug:
        var: groups

    - name: Create quick_ssh script
      copy:
        content: |
            #!/bin/bash
            ssh -i {{ ANSIBLE_REPO_PATH }}/workdir/{{ guid }}key {{ remote_user }}@{{ groups[('tag_' ~ env_type ~ '_' ~ guid ~ '_bastion') | replace('-', '_')].0 }}
        dest: '{{ ANSIBLE_REPO_PATH }}/workdir/{{ guid }}-quickssh.sh'
        mode: 0755
    # when: delete_app_post_deploy

    - name: Create empty local ssh config as defined by deploy_local_ssh_config_location
      file:
        dest: "{{ ANSIBLE_REPO_PATH }}/workdir/{{ env_type }}_{{ guid }}_ssh_conf"
        state: touch

