---
- name: SSH Config Setup
  hosts: 
    - localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - checkpoint-resume
  vars:
    - cloud_template: "{{ lookup( 'file', '{{ ANSIBLE_REPO_PATH }}/workdir/{{cloud_provider}}_cloud_template.{{ env_type }}.{{ guid }}.template') | from_yaml }}"
    # This declaration is part of a workaround for a known bug in ansible.  
    - extra_host_groups:
        - name: 'localhost'
          hosts:
            - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_localhost') | replace('-', '_') }}"
    - bastion_assigned_hostname: bastion-REPL.rhpds.opentlc.com
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
  tasks:
    - name: add bastion public hostname
      add_host:
        name: "{{ ravello_groups | json_query('_meta.hostvars.\"' ~ bastion_assigned_hostname ~ '\".externalFqdn') }}"
        groups: 
        - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_bastion_public') | replace('-', '_') }}"
        - "{{ ('tag_Project_' ~ env_type ~ '_' ~ guid) | replace('-', '_') }}"
    - name: add bastion internal hostname
      add_host:
        name: "{{ bastion_assigned_hostname }}"
        groups: 
        - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_bastion') | replace('-', '_') }}"
        - "{{ ('tag_Project_' ~ env_type ~ '_' ~ guid) | replace('-', '_') }}"
    - name: add remaining hosts
      add_host:
        name: "{{ item['hostnames'].0 }}"
        groups:
          - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_' ~ item.tag ) | replace('-', '_') }}"
          - "{{ ('tag_Project_' ~ env_type ~ '_' ~ guid) | replace('-', '_') }}"
      with_items: "{{ cloud_template['vms'] }}"
      when: item.tag != 'bastion'
    # This task is part of a workaround for a known bug in ansible
    - name: add localhost group
      add_host:
        name: localhost
        groups:
        - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_localhost') | replace('-', '_') }}"

    - debug:
        var: item.0
      with_subelements:
        - "{{ extra_host_groups }}"
        - hosts 

    - debug:
        var: item.1
      with_subelements:
        - "{{ extra_host_groups }}"
        - hosts 

    - name: add extra host groups
      add_host:
        name: "{{hostvars['localhost']['groups'][item.1].0}}"
        groups: "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_' ~ item.0.name) | replace('-','_') }}"
      with_subelements:
        - "{{ extra_host_groups }}"
        - hosts 

    - name: bastion_ip
      debug:
        msg: "{{ hostvars[hostvars['localhost']['groups'][('tag_' ~ env_type ~ '_' ~ guid ~ '_bastion') | replace('-', '_')].0] }}"
      ignore_errors: yes

    - debug:
        var: groups

    - name: Create quick_ssh script
      copy:
        content: |
            #!/bin/bash
            ssh -i {{ ANSIBLE_REPO_PATH }}/workdir/{{ guid }}key {{ remote_user }}@{{ groups[('tag_' ~ env_type ~ '_' ~ guid ~ '_bastion_public') | replace('-', '_')].0 }}
        dest: '{{ ANSIBLE_REPO_PATH }}/workdir/{{env_type}}-{{ guid }}-quickssh.sh'
        mode: 0755
    # when: delete_app_post_deploy

    - name: Create empty local ssh config as defined by deploy_local_ssh_config_location
      file:
        dest: "{{ ANSIBLE_REPO_PATH }}/workdir/{{ env_type }}_{{ guid }}_ssh_conf"
        state: touch
    - debug:
        var: hostvars['groups']

