---
# tasks file for checkpoint-freeze
# Create blueprint from existing app
  - hosts: localhost
    vars_files:
      - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
      - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
    vars:
     - checkpoint_prefix: ""
    tags:
      - checkpoint-save
      - checkpoint-freeze
    tasks: 
     - local_action:
         module: ravello_app
         name: '{{ application_name }}'
         app_name: '{{ application_name }}'
#        state: 'stopped'
         blueprint_name: '{{ checkpoint_prefix }}{{ env_type }}.{{ checkpoint_id }}-bp'
         blueprint_description: 'Blueprint of app {{ env_type }}.{{ checkpoint_id }}'
         state: blueprint
       register: design_results
     - copy:
         src: "{{ ANSIBLE_REPO_PATH }}/workdir/{{ env_authorized_key }}"
         dest: "{{ ANSIBLE_REPO_PATH }}/workdir/{{ design_results.blueprint_id }}-checkpoint.key"
         mode: 0600
         owner: root
