---

- name: Create env key
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    - checkpoint_resume: false
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
  tags:
    - step003
    - generate_env_keys
  tasks:
    - name: Generate SSH keys
      shell: 'ssh-keygen -b 2048 -t rsa -f {{ ANSIBLE_REPO_PATH }}/workdir/{{env_authorized_key}} -q -N ""'
      args:
        creates: "{{ ANSIBLE_REPO_PATH }}/workdir/{{env_authorized_key}}"
      when: set_env_authorized_key
      tags:
        - skip-resume
    - local_action: command whoami
      register: my_login
    - local_action: command hostname
      register: my_domain
    - set_fact:
        my_login_domain: '{{ my_login.stdout_lines.0 }}@{{ my_domain.stdout_lines.0 }}'
    - name: save ssh_keys as facts
      set_fact:
        env_public_key: "{{ lookup('file', '{{ ANSIBLE_REPO_PATH }}/workdir/{{ env_authorized_key }}.pub') | regex_replace(' ' + my_login_domain, '') }}"
      
    - debug:
        var: checkpoint_resume
    - copy:
        src: "{{ ANSIBLE_REPO_PATH }}/workdir/{{ blueprint_id }}-checkpoint.key"
        dest: "{{ ANSIBLE_REPO_PATH }}/workdir/{{ env_authorized_key }}"
        mode: 0600
        owner: root
      when: checkpoint_resume
    - copy:
        src: "{{ ANSIBLE_REPO_PATH }}/workdir/{{ blueprint_id }}-checkpoint.key.pub"
        dest: "{{ ANSIBLE_REPO_PATH }}/workdir/{{ env_authorized_key }}.pub"
        mode: 0600
        owner: root
      when: checkpoint_resume
